export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/discover/index',
    'pages/trip-detail/index',
    'pages/trip-create/index',
    'pages/trip-edit/index',
    'pages/trip-participants/index',
    'pages/trip-comments/index',
    'pages/trip-manage-participants/index',
    'pages/trip-timeline-edit/index',
    'pages/trip-checklist-edit/index',
    'pages/trip-budget-edit/index',
    'pages/trip-vote-detail/index',
    'pages/trip-chat/index',
    'pages/messages/index',
    'pages/notification-detail/index',
    'pages/comment-replies/index',
    'pages/friends/index',
    'pages/friend-requests/index',
    'pages/add-friend/index',
    'pages/friend-groups/index',
    'pages/friend-profile/index',
    'pages/frequent-friends/index',
    'pages/profile/index',
    'pages/profile-edit/index',
    'pages/settings/index',
    'pages/privacy-settings/index',
    'pages/blacklist/index',
    'pages/login/index',
    'pages/phone-auth/index',
    'pages/complete-profile/index',
    'pages/share-invite/index',
    'pages/invite-landing/index',
    'pages/qrcode-landing/index',
    'pages/invite-poster/index',
    'pages/vote/index',
    'pages/trip-review/index',
    'pages/trip-templates/index',
    'pages/year-in-review/index',
    'pages/announcements/index',
    'pages/report/index',
    'pages/report-management/index',
    'pages/sensitive-words/index',
    'pages/admin-stats/index',
    'pages/account-deletion/index',
    'pages/data-export/index',
    'pages/agreement/index',
  ],
  tabBar: {
    color: '#999',
    selectedColor: '#2563EB',
    backgroundColor: '#ffffff',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/index/index',
        text: '行程圈',
        iconPath: 'assets/tabbar/home.png',
        selectedIconPath: 'assets/tabbar/home-active.png',
      },
      {
        pagePath: 'pages/discover/index',
        text: '发现',
        iconPath: 'assets/tabbar/discover.png',
        selectedIconPath: 'assets/tabbar/discover-active.png',
      },
      {
        pagePath: 'pages/trip-create/index',
        text: '发布',
        iconPath: 'assets/tabbar/create.png',
        selectedIconPath: 'assets/tabbar/create-active.png',
      },
      {
        pagePath: 'pages/messages/index',
        text: '消息',
        iconPath: 'assets/tabbar/message.png',
        selectedIconPath: 'assets/tabbar/message-active.png',
      },
      {
        pagePath: 'pages/profile/index',
        text: '我的',
        iconPath: 'assets/tabbar/profile.png',
        selectedIconPath: 'assets/tabbar/profile-active.png',
      },
    ],
  },
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#2563EB',
    navigationBarTitleText: 'TripCircle',
    navigationBarTextStyle: 'white',
    backgroundColor: '#F8FAFC',
  },
  // 组件按需注入，减小包体积
  lazyCodeLoading: 'requiredComponents',
  // 定位权限声明（微信小程序必须）
  permission: {
    'scope.userLocation': {
      desc: '用于获取你的位置，以便展示附近的行程',
    },
  },
  requiredPrivateInfos: ['getLocation'],
})
